---
#ConfgMap to setup parameters for user workload monitoring.
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      # retention: 15d
      enforcedSampleLimit: 50000
      # enforcedLabelLimit: 500 
      # enforcedLabelNameLengthLimit: 50 
      # enforcedLabelValueLengthLimit: 600 
      externalLabels:
        smartops_source: user-workload-monitoring
        smartops: newton
      remoteWrite:
        - url: "http://prometheus-kafka-adapter.prom-kafka-adapter.svc.cluster.local:8080/receive"
          writeRelabelConfigs:
          - sourceLabels:
            - __tmp_openshift_cluster_id__ 
            targetLabel: cluster_id 
            action: replace 
          - sourceLabels: [__name__]
            # https://github.com/sustainable-computing-io/kepler/blob/424d2f88d2c050a354c023e8b830afefd312baf4/pkg/collector/collector.go#L28-L43
            regex: "pod_energy_stat|pod_total_energy_millijoule|pod_total_(.*)|pod_curr_(.*)|node_energy_stat|node_(.*)|idrac_(.*)"
            action: keep
    # thanosRuler:
    #   retention: 15d



