---
#ConfgMap to setup parameters for cluster level monitoring.
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    # Enable user workload montoring
    enableUserWorkload: true
    prometheusK8s:
      # Keep data stored for 15 days
      # retention: 15d
      externalLabels:
        smartops_source: cluster-monitoring
        smartops: newton
      remoteWrite:
        - url: "http://prometheus-kafka-adapter.prom-kafka-adapter.svc.cluster.local:8080/receive"
          writeRelabelConfigs:
          - sourceLabels:
            - __tmp_openshift_cluster_id__ 
            targetLabel: cluster_id 
            action: replace 
          - sourceLabels: [__name__]
            #regex: "node_cpu_(.*)|node_hwmon_(.*)|node_intr_total|node_load(.*)|node_memory(.*)|pod_(.*)|kube_pod_info|kube_pod_labels|kube_node_container(.*)|kube_node_status(.*)"
            # Without pods labels
            regex: "node_cpu_(.*)|node_hwmon_(.*)|node_intr_total|node_load(.*)|node_memory(.*)|pod_(.*)|kube_pod_info|kube_node_container(.*)|kube_node_status(.*)|idrac_(.*)"
            action: keep
    # alertmanagerMain:
    #   retention: 15d
