apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    #app.kubernetes.io/component: exporter
    #app.kubernetes.io/name: node-exporter-custom
    smartops: newton
  name: node-exporter-custom
  namespace: newton
spec:
  endpoints:
  - interval: 15s
    port: exporter-custom
    scheme: http
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: pod_node_name
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: node-exporter-custom
